import{translateQuizzes}from'./quiz-ar.js';
import{translateTaskGoals}from'./task-translations.js';
import{installLanguage,translations}from'./language.js';
import{source18}from'./source18.js';
import{extendCurriculum,passesWorkplace}from'./workplace.js';
extendCurriculum(levels);
import{verifyObjectives}from'./completion.js';
import{levels,extras}from'./curriculum.js';
import{PracticeShell}from'./practical-shell.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shell=new PracticeShell();let source={commands:[],pages:[]},sourceError=false;
let progress={tasks:{},exams:{},name:'Student'},storageAvailable=true;
try{const old=JSON.parse(localStorage.getItem('rockylab-v1')||'null');if(old&&old.tasks&&old.exams)progress={...progress,...old}}catch{storageAvailable=false}
let localPDF=null,real=null,terminalLog='RockyLab / personal training environment\n\nEducational simulator · no real Linux VM is running here.\nSupported commands operate on a practice filesystem in memory.\nUse My servers to connect an actual Rocky Linux host.\n\nTry: whoami\n',busy=false,exam=null,timer=null;
const save=()=>{try{localStorage.setItem('rockylab-v1',JSON.stringify(progress))}catch{storageAvailable=false;toast('Browser storage unavailable. Export progress before leaving.')}};
function toast(s){const el=$('#toast');el.textContent=s;el.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>el.style.display='none',4300)}
const btn=(label,attrs='',primary=false)=>'<button class="'+(primary?'primary':'')+'" '+attrs+'>'+label+'</button>';
const href=(label,path,primary=false)=>'<a class="'+(primary?'primary':'')+'" style="padding:8px 13px;border-radius:6px" href="'+path+'">'+label+'</a>';
function foot(){return'<footer>Independent personal study project · Rocky Linux practice · Based on the supplied RH124 lectures 1–18. Not an official Red Hat course or certification exam. <a class="text-link" href="#book">Source & corrections</a></footer>'}
function page(content){$('#app').innerHTML='<div class="page">'+content+foot()+'</div>'}
function head(k,title,desc,actions=''){return'<div class="page-head"><div><p class="eyebrow">'+k+'</p><h1>'+title+'</h1><p>'+desc+'</p></div><div class="actions">'+actions+'</div></div>'}
function done(l){return l.tasks.filter(t=>progress.tasks[l.id+'-'+t.check]).length}
function taskCount(){return levels.reduce((s,l)=>s+done(l),0)}
function levelsPage(){
page(head('LEARNING PATH','Build your Linux instincts.','26 levels. One command at a time.',href('Continue training →','#lab/'+(progress.lastLevel||3),true))+
'<div class="stats"><div class="stat"><b>'+taskCount()+' / '+levels.reduce((n,l)=>n+l.tasks.length,0)+'</b><span>Practical objectives completed</span></div><div class="stat"><b>18</b><span>Source lectures · practical additions integrated</span></div><div class="stat"><b>'+Object.keys(progress.exams).length+'</b><span>Exams attempted</span></div></div>'+
'<div class="filters"><input id="level-search" type="search" placeholder="Find a mission, topic or command…" aria-label="Find a mission"><select id="level-filter" aria-label="Filter levels"><option value="all">All levels</option><option value="RH124">RH124 core</option><option value="Extended">Extended skills</option><option value="remaining">Not completed</option></select></div><div id="level-grid" class="grid"></div>');
const draw=()=>{let q=$('#level-search').value.toLowerCase(),f=$('#level-filter').value;let matches=levels.filter(l=>(f==='all'||l.source===f||f==='remaining'&&done(l)<l.tasks.length)&&JSON.stringify(l).toLowerCase().includes(q));$('#level-grid').innerHTML=matches.map(l=>'<section class="card"><div class="row" style="border:0;padding:0"><span class="index">'+String(l.id).padStart(2,'0')+'</span><span class="tag">'+l.source+'</span></div><h2>'+esc(l.title)+'</h2><p>'+l.description+'</p><div class="meta">'+l.category+' · '+l.difficulty+'<br>'+l.tasks.length+' objectives · '+l.quiz.length+' quiz questions'+(l.tasks.some(t=>t.real)?' · Real lab required':' · Simulator ready')+'</div><progress max="'+l.tasks.length+'" value="'+done(l)+'"></progress><div class="progress-label"><span>'+done(l)+'/'+l.tasks.length+' objectives</span><span>'+l.tasks.length*20+' XP</span></div><div class="actions">'+href('Open mission →','#lab/'+l.id,true)+href('Study','#lesson/'+l.id)+'</div></section>').join('')||'<p>No matching missions.</p>'};draw();$('#level-search').oninput=draw;$('#level-filter').onchange=draw}
function renderLab(id){const l=levels.find(x=>x.id===id);if(!l){page('<h1>Mission not found</h1>'+href('Browse missions','#levels'));return}progress.lastLevel=id;save();
$('#app').innerHTML='<div class="workspace"><section class="lesson"><div class="crumb"><a href="#levels">← All missions</a><span>'+String(id).padStart(2,'0')+' / '+levels.length+'</span></div><p class="eyebrow">'+l.source+' / '+l.category+'</p><h1>'+l.title+'</h1><p>'+l.description+'</p><div class="badges"><span>'+l.category.toUpperCase()+'</span><span>'+l.difficulty.toUpperCase()+'</span><span>'+l.tasks.length*20+' XP</span></div><div class="progress-label"><span>Mission progress</span><b>'+done(l)+' / '+l.tasks.length+'</b></div><progress max="'+l.tasks.length+'" value="'+done(l)+'"></progress><div class="actions" style="margin-top:18px">'+href('Read lesson','#lesson/'+id)+href('Level exam','#exam/'+id)+'</div><div class="tasks">'+l.tasks.map((t,i)=>{const complete=progress.tasks[id+'-'+t.check];return'<details class="task '+(complete?'done':'')+'" '+(i===l.tasks.findIndex(x=>!progress.tasks[id+'-'+x.check])?'open':'')+'><summary><span class="task-num">'+(complete?'✓':i+1)+'</span><div><b>'+t.title+'</b><small>'+(t.lecture?'Lecture '+t.lecture+' · ':'Additional practice · ')+(t.real?'Real Rocky lab':'Guided practice')+(complete?' · '+(complete.mode==='real'?'server checked':'simulator checked'):'')+'</small></div></summary><div class="task-body"><p>'+t.description+'</p>'+(t.simulatorOnly&&real?'<div class="callout">Browser filesystem exercise. Switch to simulator to complete it.</div>':'')+(t.real&&!real?'<div class="callout">This objective requires your real server. <a class="text-link" href="#server">Connect a lab →</a></div>':'')+'<details><summary style="padding:8px 0;font-size:14px">Command example</summary><pre class="code">'+esc(t.command)+'</pre>'+btn('Load into terminal','data-load="'+i+'"')+'</details><div class="actions">'+btn('Check objective','data-check="'+i+'"',true)+btn('Hint','data-hint="'+i+'"')+'</div><div id="task-feedback-'+i+'" role="status"></div></div></details>'}).join('')+'</div>'+href(id<levels.length?'Next mission →':'All missions',id<levels.length?'#lab/'+(id+1):'#levels')+'</section><section class="terminal"><div class="terminal-head"><strong>LINUX TERMINAL</strong><span>'+(real?'REAL LAB · CONNECTED':'SIMULATOR · LOCAL')+'</span></div><div class="terminal-sub">'+(real?esc(real.label)+' · Non-interactive runner · 20s command limit':'student@rocky · Practice filesystem · No server connection')+'</div><pre id="terminal-output" aria-label="Terminal output" tabindex="0"></pre><form id="shell"><label for="command">'+(real?'lab':'student@rocky')+':'+(real?'~':esc(shell.cwd.replace('/home/student','~')))+' $</label><textarea id="command" rows="2" spellcheck="false" aria-label="Terminal command"></textarea><button class="primary" '+(busy?'disabled':'')+'>Run ↵</button></form><div class="terminal-foot"><span>'+(real?'Cockpit: Vim, top and interactive SSH':'Enter: run · Shift+Enter: new line · ↑ ↓ history · Auto-check enabled')+'</span>'+btn('Clear','id="clear-terminal"')+'</div></section></div>';
$('#terminal-output').textContent=terminalLog;$('#terminal-output').scrollTop=$('#terminal-output').scrollHeight;
let hi=shell.history.length;
$('#command').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#shell').requestSubmit();return}if(e.key==='ArrowUp'&&!$('#command').value.includes('\n')){e.preventDefault();$('#command').value=shell.history[Math.max(0,--hi)]||''}if(e.key==='ArrowDown'&&!$('#command').value.includes('\n')){e.preventDefault();$('#command').value=shell.history[Math.min(shell.history.length,++hi)]||''}if(e.key==='Tab'){e.preventDefault();const m=['whoami','pwd','ls','cd','cat','mkdir','touch','echo','cp','mv','chmod','systemctl','journalctl','hostname','grep','history'].filter(x=>x.startsWith($('#command').value));if(m.length===1)$('#command').value=m[0]+' '}if(e.ctrlKey&&e.key==='l'){e.preventDefault();terminalLog='';$('#terminal-output').textContent=''}};
$('#shell').onsubmit=async e=>{e.preventDefault();const cmd=$('#command').value.trim();if(!cmd||busy)return;$('#command').value='';await execute(cmd,id)};
$('#clear-terminal').onclick=()=>{terminalLog='';$('#terminal-output').textContent=''};
document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{$('#command').value=l.tasks[Number(b.dataset.load)].command;$('#command').focus()});
document.querySelectorAll('[data-hint]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.hint);$('#task-feedback-'+i).innerHTML='<p class="hint">'+esc(l.tasks[i].hint)+'</p>'});
document.querySelectorAll('[data-check]').forEach(b=>b.onclick=async()=>{if(busy)return;const i=Number(b.dataset.check),t=l.tasks[i];if(t.simulatorOnly&&real){toast('This exercise uses the browser filesystem. Switch to simulator.');return}if(t.real&&!real){toast('Connect your real Rocky server to check this objective.');return}let success=false;try{if(real){const r=await api('/check',{level:id,check:t.check});success=r.passed}else success=t.check.startsWith('work-')?passesWorkplace(shell,t.check):!!shell.check(t.check)}catch(e){toast(e.message);return}if(success){progress.tasks[id+'-'+t.check]={at:new Date().toISOString(),mode:real?'real':'simulator'};save();renderLab(id);toast('Objective verified · +20 XP (awarded once)')}else $('#task-feedback-'+i).innerHTML='<p class="incorrect">Not yet. Run the required steps, verify the result, then try again.</p>'});
}
async function execute(cmd,id){busy=true;terminalLog+='\n$ '+cmd+'\n';const input=$('#command'),runButton=$('#shell button');if(runButton)runButton.disabled=true;let completed=[];try{const r=real?await api('/run',{command:cmd}):shell.run(cmd);if(cmd==='clear')terminalLog='';else terminalLog+=(r.out||'(no output)')+'\n'+(r.code?'[exit '+r.code+']\n':'');const level=levels.find(l=>l.id===id);completed=await verifyObjectives(level,progress,async check=>real?(await api('/check',{level:id,check})).passed:(check.startsWith('work-')?passesWorkplace(shell,check):!!shell.check(check)),real?'real':'simulator');if(completed.length){save();terminalLog+='✓ '+completed.length+' objective(s) completed automatically · +'+completed.length*20+' XP\n'}}catch(e){terminalLog+='Error: '+e.message+'\n'}finally{busy=false;if(location.hash==='#lab/'+id){renderLab(id);$('#command')?.focus()}if(completed.length)toast('✓ '+completed.length+' completed automatically / اكتمل التدريب تلقائياً')}}
function commandHTML(r){return'<details class="ref-item" id="'+esc(r.id)+'"><summary><h2>'+esc(r.name)+'</h2><span class="tag">'+(r.source==='18-lecture guide'?'Lecture '+r.lecture+' · PDF p. '+r.page:r.page?'Earlier guide · p. '+r.page:'Additional practice')+'</span></summary><p class="'+(r.source==='RH124 PDF'?'ar':'')+'">'+esc(r.description)+'</p><pre class="code">'+esc(r.example||r.syntax)+'</pre><p class="'+(r.source==='RH124 PDF'?'ar':'')+'">'+esc(r.notes).replaceAll('\n','<br>')+'</p><div class="actions">'+btn('Copy example','data-copy="'+esc(r.id)+'"')+href('Related lesson','#lesson/'+r.level)+(r.page?'<a class="text-link" href="#book">Original: page '+r.page+'</a>':'')+'</div></details>'}
function wireCopy(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const r=[...source.commands,...extras,...source18].find(x=>x.id===b.dataset.copy);try{await navigator.clipboard.writeText(r.example||r.syntax);toast('Example copied')}catch{toast('Clipboard unavailable. Select and copy the example.')}})}
function reference(){page(head('COMMAND LIBRARY','Understand the command.','Syntax, examples and source pages — with extended admin tools.',href('Source & corrections','#book'))+'<div class="filters"><input type="search" id="ref-search" placeholder="Search commands, flags, explanations…" aria-label="Search command library"><select id="ref-level" aria-label="Filter command topic"><option value="">All topics</option>'+levels.map(l=>'<option value="'+l.id+'">'+l.id+' · '+l.title+'</option>').join('')+'</select></div><p id="ref-count" class="muted"></p><div id="ref-results"></div>');const draw=()=>{let q=$('#ref-search').value.toLowerCase(),n=$('#ref-level').value;const r=[...source.commands,...extras,...source18].filter(x=>(!n||x.level===Number(n))&&JSON.stringify(x).toLowerCase().includes(q));$('#ref-count').textContent=r.length+' command cards · Source examples are study material, not all are simulated.'+(sourceError?' Source could not load; showing extended commands.':'');$('#ref-results').innerHTML=r.map(commandHTML).join('')||'<p>No commands found.</p>';wireCopy()};draw();$('#ref-search').oninput=draw;$('#ref-level').onchange=draw}
function lesson(id){const l=levels.find(x=>x.id===id);if(!l){levelsPage();return}const cards=[...source.commands,...extras,...source18].filter(r=>r.level===id);page(head(l.source+(l.lecture?' / LECTURE '+l.lecture:' / ADDITIONAL PRACTICE')+' / LEVEL '+id,l.title,l.description,href('Practice this level →','#lab/'+id,true))+'<section class="card"><h2>The idea</h2><p class="ar">'+l.concept+'</p><div class="meta">'+(l.lecture?'Source: 18-lecture guide, pages '+l.pages:'Additional training beyond the original 14 lectures')+'</div></section><h2>What you will do</h2>'+l.tasks.map((t,i)=>'<article><p class="eyebrow">OBJECTIVE '+(i+1)+'</p><h2>'+t.title+'</h2><p>'+t.description+'</p><pre class="code">'+esc(t.command)+'</pre><p>'+t.hint+'</p></article>').join('')+'<h2>Command explanations</h2>'+cards.map(commandHTML).join('')+(cards.length===0?'<p>Review the concepts above and the original PDF for this introductory lecture.</p>':'')+'<div class="actions" style="margin-top:25px">'+href('Start practice','#lab/'+id,true)+href('Take level exam','#exam/'+id)+'</div>');wireCopy()}
function examsPage(){page(head('ASSESSMENTS','Test what you can do.','Per-level quizzes and a timed mixed review. Practice exams, not certification scoring.')+'<section class="card"><p class="eyebrow">FINAL REVIEW</p><h2>System Administrator Challenge</h2><p>26 questions sampled across all levels · 30 minutes · 80% pass mark. Answers and explanations appear after submission.</p>'+href('Start timed exam →','#exam/final',true)+'</section><div class="grid">'+levels.map(l=>'<section class="card"><span class="tag">LEVEL '+l.id+'</span><h2>'+l.title+'</h2><p>3 questions · Pass: all 3 correct</p><p>'+(progress.exams[l.id]?'Best score: '+progress.exams[l.id].best+'%':'Not attempted')+'</p>'+href('Take exam','#exam/'+l.id)+'</section>').join('')+'</div>')}
function startExam(key){if(timer)clearInterval(timer);const id=Number(key),l=levels.find(x=>x.id===id);if(key!=='final'&&!l){examsPage();return}const pool=key==='final'?levels.map(l=>({...l.quiz[Math.floor(Math.random()*l.quiz.length)],level:l.id})):l.quiz.map(q=>({...q,level:id}));exam={key,questions:pool,answers:{},deadline:key==='final'?Date.now()+30*60000:null,submitted:false};drawExam();if(exam.deadline)timer=setInterval(()=>{if(!exam||exam.submitted)return;if($('#exam-timer'))$('#exam-timer').textContent=Math.max(0,Math.ceil((exam.deadline-Date.now())/60000))+' minutes left';if(Date.now()>=exam.deadline)submitExam()},1000)}
function drawExam(){const ex=exam;page(head('EXAM / '+(ex.key==='final'?'MIXED REVIEW':'LEVEL '+ex.key),ex.key==='final'?'System Administrator Challenge':levels.find(l=>l.id===Number(ex.key)).title,'Choose one answer per question. Review explanations after submitting.','<span id="exam-timer" class="tag">'+(ex.deadline?'30 minutes left':'No time limit')+'</span>')+'<form id="exam-form">'+ex.questions.map((q,i)=>'<section class="quiz-question"><p class="eyebrow">QUESTION '+(i+1)+' / '+ex.questions.length+' · '+(q.lecture?'LECTURE '+q.lecture:'ADDITIONAL PRACTICE')+'</p><h2>'+esc(q.question)+'</h2>'+q.options.map((o,j)=>'<label><input type="radio" name="q'+i+'" value="'+j+'">'+esc(o)+'</label>').join('')+'</section>').join('')+btn('Submit exam','type="submit"',true)+'</form><div id="exam-result"></div>');$('#exam-form').onchange=e=>{exam.answers[Number(e.target.name.slice(1))]=Number(e.target.value)};$('#exam-form').onsubmit=e=>{e.preventDefault();submitExam()}}
function submitExam(){if(!exam||exam.submitted)return;exam.submitted=true;clearInterval(timer);let correct=exam.questions.filter((q,i)=>exam.answers[i]===q.answer).length,score=Math.round(correct/exam.questions.length*100),passed=score>=(exam.key==='final'?80:100);const old=progress.exams[exam.key];progress.exams[exam.key]={best:Math.max(old?.best||0,score),last:score,attempts:(old?.attempts||0)+1,at:new Date().toISOString()};save();$('#exam-form').querySelectorAll('input,button').forEach(el=>el.disabled=true);$('#exam-result').innerHTML='<section class="result"><b>'+score+'% · '+(passed?'Passed':'Keep practicing')+'</b><p>'+correct+' / '+exam.questions.length+' correct. Unanswered questions count as incorrect.</p></section>'+exam.questions.map((q,i)=>'<article><b class="'+(exam.answers[i]===q.answer?'correct':'incorrect')+'">'+(i+1)+'. '+(exam.answers[i]===q.answer?'Correct':'Review this')+'</b><p>Correct answer: '+esc(q.options[q.answer])+'</p><p>'+esc(q.explanation)+'</p>'+href('Review level '+q.level,'#lesson/'+q.level)+'</article>').join('')+btn('Try again','id="retry-exam"');$('#retry-exam').onclick=()=>startExam(exam.key);$('#exam-result').scrollIntoView({behavior:'smooth'})}
function serverPage(){page(head('REAL LAB','Your Rocky machines.','Connect a real command runner, or use Cockpit for a full interactive terminal.')+'<div class="callout ar">المحاكي يعمل فوراً بدون سيرفر. التطبيق الحقيقي يحتاج VM أو VPS خاص بيك. GitHub Pages يستضيف الواجهة فقط. شغّل بوابة المختبر من ملفات المشروع ثم اربط عنوانها هنا. رمز البوابة يبقى بذاكرة الصفحة فقط ولا ينحفظ.</div><div class="two"><section class="card"><h2>Connect the command runner</h2><form id="server-form" class="server-form"><label for="gateway">Gateway URL</label><input id="gateway" type="url" placeholder="https://lab.example.com" required><label for="gateway-token">Access token</label><input id="gateway-token" type="password" autocomplete="off" required placeholder="Your lab gateway token"><label for="server-label">Server label</label><input id="server-label" value="My Rocky lab" maxlength="60"><div class="actions" style="margin-top:22px">'+btn('Connect & verify','type="submit"',true)+btn('Use simulator','type="button" id="disconnect"')+'</div><p id="connection-status" role="status">'+(real?'Connected: '+esc(real.label):'No real server connected.')+'</p></form></section><section class="card"><h2>Interactive terminal</h2><p>The runner supports finite commands and automated checks. For Vim, top, passwd, ssh-keygen prompts and a persistent shell, open your Cockpit terminal.</p><form id="cockpit-form" class="server-form"><label for="cockpit-url">Cockpit URL</label><input id="cockpit-url" type="url" placeholder="https://your-server:9090" required><div class="actions">'+btn('Open Cockpit ↗','type="submit"')+'</div></form><p>Use your server account. The website never asks for your SSH private key.</p></section><section class="card wide"><h2>Two-host SSH lab</h2><p>Use two Rocky VMs: server A for the runner, and server B for remote login. Use a private lab network or VPN. In server A’s SSH config, create an alias named <code>lab-b</code> pointing to server B. Verify the fingerprint and install your public key before level 13.</p><pre class="code"># In server A ~/.ssh/config — replace the address:\nHost lab-b\n    HostName SERVER_B_ADDRESS\n    User student\n    IdentityFile ~/.ssh/lab_key\n    IdentitiesOnly yes\n\n# In an interactive terminal:\nssh lab-b\nwhoami\nhostname\necho "$SSH_CONNECTION"\nexit</pre><p>Unattended checks use the gateway account’s SSH configuration and verified known_hosts. A passphrase-protected key needs an available ssh-agent. Do not disable host-key checking.</p><div class="actions"><a class="text-link" href="setup-guide.html" target="_blank" rel="noopener">Complete setup guide ↗</a><a class="text-link" href="https://docs.rockylinux.org/guides/security/ssh_public_private_keys/" target="_blank" rel="noopener">Rocky SSH documentation ↗</a></div></section></div>');
$('#server-form').onsubmit=async e=>{e.preventDefault();let url=$('#gateway').value.trim().replace(/\/+$/,'');try{const u=new URL(url);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('Use HTTPS for a remote gateway.');const candidate={url,token:$('#gateway-token').value,label:$('#server-label').value||'Rocky lab'};const r=await api('/health',null,candidate);if(r.kind!=='rockylab-gateway')throw Error('Not a compatible RockyLab gateway.');real=candidate;terminalLog+='\nConnected to real lab: '+r.hostname+'\n';$('#connection-status').textContent='Connected · '+r.hostname+' · '+r.user;$('#gateway-token').value='';toast('Real lab connected')}catch(err){$('#connection-status').textContent=err.message}};$('#disconnect').onclick=()=>{real=null;serverPage();toast('Switched to simulator')};$('#cockpit-form').onsubmit=e=>{e.preventDefault();const u=new URL($('#cockpit-url').value);if(u.protocol!=='https:'){toast('Use an HTTPS Cockpit URL.');return}window.open(u.href,'_blank','noopener,noreferrer')}}
async function api(path,data,config=real){if(!config)throw Error('No server connected');const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),25000);try{const r=await fetch(config.url+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+config.token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:ctl.signal,credentials:'omit',cache:'no-store'});const body=await r.json();if(!r.ok)throw Error(body.error||'Gateway request failed');return body}finally{clearTimeout(t)}}
function profilePage(){page(head('YOUR PROGRESS','Keep your practice moving.','Saved on this browser. Export and import to continue on another device.')+'<div class="stats"><div class="stat"><b>'+taskCount()*20+'</b><span>Practice XP</span></div><div class="stat"><b>'+levels.filter(l=>done(l)===l.tasks.length).length+' / '+levels.length+'</b><span>Completed missions</span></div><div class="stat"><b>'+Object.values(progress.exams).filter(e=>e.best>=80).length+'</b><span>Exam scores at 80% or higher</span></div></div><div class="card"><div class="actions">'+btn('Export progress','id="export-progress"',true)+'<label class="muted">Import backup <input type="file" id="import-progress" accept=".json,application/json"></label></div><p>Simulator files reset when you refresh. Completed objectives and quiz results remain in browser storage. No automatic account synchronization.</p>'+(storageAvailable?'':'<p class="incorrect">Storage unavailable. Export before leaving.</p>')+'</div>'+levels.map(l=>'<div class="row"><div><b>'+l.id+'. '+l.title+'</b><br><small>'+done(l)+'/'+l.tasks.length+' objectives · Best quiz: '+(progress.exams[l.id]?.best??'—')+'%</small></div>'+href('Continue →','#lab/'+l.id)+'</div>').join(''));
$('#export-progress').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,...progress},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rockylab-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)};$('#import-progress').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>1000000)throw Error('Choose a backup smaller than 1 MB.');const v=JSON.parse(await file.text());if(v.version!==1||!v.tasks||!v.exams||typeof v.tasks!=='object'||typeof v.exams!=='object')throw Error('Invalid progress backup.');const clean={tasks:{},exams:{},lastLevel:Math.min(levels.length,Math.max(1,Number(v.lastLevel)||3)),name:'Student'};for(const l of levels)for(const t of l.tasks){const k=l.id+'-'+t.check,val=v.tasks[k];if(val&&['simulator','real'].includes(val.mode)&&typeof val.at==='string')clean.tasks[k]={mode:val.mode,at:val.at}}for(const k of [...levels.map(l=>String(l.id)),'final','video9-quiz','video9-commands']){let e=v.exams[k];if(e&&Number.isFinite(e.best)&&e.best>=0&&e.best<=100)clean.exams[k]={best:e.best,last:Number(e.last)||0,attempts:Number(e.attempts)||1,at:typeof e.at==='string'?e.at:''}}progress=clean;save();profilePage();toast('Progress imported')}catch(err){toast(err.message)}}}
function bookPage(){page(head('SOURCE REVIEW','Your 106-page study guide.','All 18 lectures reviewed. Keep the original PDF on your own device.')+'<section class="card"><h2>Open the original privately</h2><p>Choose your RH124 PDF to read it here. It stays in this browser and is not uploaded. Mission labels use the new 18-lecture guide. Legacy command cards retain page numbers from the earlier 51-page guide.</p><label>Original PDF <input type="file" id="local-pdf" accept=".pdf,application/pdf"></label><div id="pdf-link"></div></section><section class="card"><h2>Coverage & corrections</h2><p>106 pages reviewed across all 18 lectures. '+levels.reduce((n,l)=>n+l.tasks.length,0)+' practical objectives across '+levels.length+' levels. Each task and quiz carries its lecture label; workplace additions are integrated into the matching topic.</p><p>Lectures 1–2 introduce Linux and installation; command practice starts at lecture 3. Legacy command cards retain the earlier 51-page guide numbering. The new source cards identify their lecture and page explicitly.</p><p class="ar">قُرئت صفحات الملف الجديد الـ106 كاملة. لا ننشر ملفك الأصلي. أضفنا سيناريوهات عمل وصححنا الفروق بين تعليمات RHEL 7 القديمة وRocky الحديث، خصوصاً libvirt وTigerVNC. المحاكي يدعم مجموعة تدريبية محددة؛ تبقى SSH والبرامج التفاعلية والخدمات الحقيقية ضمن المختبر الحقيقي.</p><p>ExecStart may use an absolute executable path or a simple executable name supported by systemd search rules. An sshd syntax check succeeds only with exit status 0. Key algorithms must respect crypto policy. Packages and logs vary with Rocky version and installation profile.</p></section><h2>Source-to-level map</h2>'+levels.filter(l=>l.lecture).map(l=>'<div class="row"><div><b>'+l.id+'. '+l.title+'</b><br><small>PDF pages '+l.pages+'</small></div>'+href('Read lesson →','#lesson/'+l.id)+'</div>').join('')+'<div class="row"><div><b>Final review, comparisons, diagnostics and glossary</b><br><small>PDF pages 105–106</small></div>'+href('Final challenge →','#exam/final')+'</div><h2>Additional references</h2><div class="actions"><a class="text-link" href="https://docs.rockylinux.org/books/admin_guide/" target="_blank" rel="noopener">Rocky admin guide ↗</a><a class="text-link" href="https://docs.rockylinux.org/guides/security/learning_selinux/" target="_blank" rel="noopener">SELinux ↗</a><a class="text-link" href="https://docs.rockylinux.org/guides/security/firewalld-beginners/" target="_blank" rel="noopener">firewalld ↗</a></div>');
const link=()=>{if(localPDF)$('#pdf-link').innerHTML='<p><a class="primary" style="padding:10px 15px;border-radius:6px" href="'+localPDF+'" target="_blank" rel="noopener">Open selected PDF ↗</a></p>'};link();$('#local-pdf').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.type!=='application/pdf'&&!f.name.toLowerCase().endsWith('.pdf')){toast('Select a PDF file.');return}if(localPDF)URL.revokeObjectURL(localPDF);localPDF=URL.createObjectURL(f);link()}}
function route(){const[view,key]=location.hash.slice(1).split('/');if(timer){clearInterval(timer);timer=null}if(exam&&!exam.submitted&&view!=='exam')exam=null;document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+view||a.hash==='#levels'&&['lab','lesson'].includes(view)));switch(view){case'levels':levelsPage();break;case'reference':reference();break;case'lesson':lesson(Number(key));break;case'exams':examsPage();break;case'exam':startExam(key);break;case'server':serverPage();break;case'profile':profilePage();break;case'book':bookPage();break;case'lab':renderLab(Number(key));break;default:location.hash='#lab/3';renderLab(3)}}
window.addEventListener('hashchange',route);
try{const r=await fetch('./source.json');if(!r.ok)throw Error();source=await r.json()}catch{sourceError=true}
route();
for(const r of source18)translations[r.description]=r.descriptionAR;
translateTaskGoals(levels,translations);
translateQuizzes(levels,translations);
installLanguage(levels,route);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_training_level',description:'Open a RockyLab level. Does not execute commands or complete objectives.',inputSchema:{type:'object',properties:{level:{type:'integer',minimum:1,maximum:26}},required:['level'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async({level})=>{if(!Number.isInteger(level)||level<1||level>26)throw Error('Level must be an integer from 1 to 26.');location.hash='#lab/'+level;renderLab(level);return{level,title:levels[level-1].title,mode:real?'real':'simulator'}}})).catch(()=>{})}catch{}}




