import{questions,commands,grade}from './lecture9-data.js';
function shuffledQuiz(){return questions.map(q=>{const order=q.options.map((text,index)=>({text,index}));for(let i=order.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[order[i],order[j]]=[order[j],order[i]]}return{...q,options:order.map(o=>o.text),answer:order.findIndex(o=>o.index===q.answer)}})}
const root=document.querySelector('#lecture'),key='rockylab-lecture9-v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const video=(t=0)=>`https://www.youtube.com/watch?v=bJ1pIGZCCiY&t=${t}s`;
const stamp=t=>Math.floor(t/60)+':'+String(t%60).padStart(2,'0');
let saved={},storageOK=true,session=null;
try{saved=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{storageOK=false}
function home(){session=null;root.innerHTML=`<p class="eyebrow">RH124 / VIDEO LECTURE 09</p><h1>إدارة العمليات — اختبر فهمك</h1><p>المحاضرة التاسعة للمهندسة عبير حسني / Free4Arab · قرابة 50 دقيقة.</p><p>أسئلة أصلية أُعدّت بعد مراجعة التفريغ العربي الآلي للمحاضرة كاملة، مع تدقيق المفاهيم في أدلة Linux. روابط الوقت تعيدك إلى بداية الشرح التقريبية.</p><div class="actions"><a class="text-link" href="${video()}" target="_blank" rel="noopener">شاهد المحاضرة ↗</a><a class="text-link" href="index.html#lesson/9">شرح المستوى 9</a></div>
<div class="review-grid"><section class="card"><h2>اختبار الفهم</h2><p>${questions.length} سؤال اختيار من متعدد · كل أجزاء المحاضرة · النجاح 80%.</p><p>أفضل نتيجة: ${saved.quiz?.best??'—'}%</p><button class="primary" id="start-quiz">ابدأ اختبار الفهم</button></section><section class="card"><h2>اختبار كتابة الأوامر</h2><p>${commands.length} تحديًا · اكتب الأمر بنفسك · النجاح 80%. تصحيح للصيغ المطلوبة؛ ليس تنفيذًا على Linux.</p><p>أفضل نتيجة: ${saved.commands?.best??'—'}%</p><button class="primary" id="start-commands">ابدأ اختبار الأوامر</button></section></div>
<section class="card"><h2>مراجعة حسب الوقت</h2><div class="actions">${[[0,'العمليات وPID'],[272,'ps و/proc'],[1073,'top والمراقبة'],[1600,'Foreground وBackground'],[1952,'dd وأجهزة البيانات'],[2150,'الإشارات والإنهاء'],[2534,'nice وrenice'],[2928,'Zombie']].map(([t,name])=>`<a class="text-link" href="${video(t)}" target="_blank" rel="noopener">${stamp(t)} · ${name}</a>`).join('')}</div></section>
<details class="card"><summary>نقاط مصححة قبل الاختبار</summary><ul><li>TIME في ps هو وقت CPU المتراكم، وTTY=? تعني عدم وجود controlling terminal.</li><li>Load average ليس نسبة CPU مئوية. وSIGHUP لا تعيد تحميل كل برنامج تلقائيًا.</li><li>إنهاء الأب لا يقتل كل الأبناء تلقائيًا؛ Zombie انتهت وتنتظر جمع حالة خروجها، وتختلف عن orphan.</li><li>nice يضيف إلى القيمة الموروثة؛ لا يمنح المستخدم العادي رفع الأولوية لمجرد أن القيمة المطلوبة موجبة.</li><li>/dev/random و/dev/urandom يستخدمان مولّد النظام العشوائي؛ الفرق ليس اعتماد أحدهما فقط على حركة الماوس.</li></ul><p>تُصحّح الإجابات وفق سلوك Linux، بما في ذلك هذه التوضيحات.</p><div class="actions"><a class="text-link" href="https://man7.org/linux/man-pages/man1/ps.1.html">ps</a><a class="text-link" href="https://man7.org/linux/man-pages/man1/top.1.html">top</a><a class="text-link" href="https://man7.org/linux/man-pages/man7/signal.7.html">signals</a><a class="text-link" href="https://www.gnu.org/software/bash/manual/html_node/Job-Control-Basics.html">Bash jobs</a><a class="text-link" href="https://man7.org/linux/man-pages/man1/renice.1.html">renice</a></div></details>
<section class="card"><h2>تطبيق فعلي بعد الاختبار</h2><p>افتح Terminal تفاعليًا على Rocky أو Cockpit. نفّذ sleep 300، أوقفه بـ Ctrl+Z، افحص jobs -l، ثم bg %1 وبعده fg %1 وأخيرًا Ctrl+C. استخدم رقم المهمة الذي يعرضه jobs بدل %1 إذا اختلف. هذه الخطوات تتطلب جلسة مستمرة؛ اختبار الكتابة أعلاه لا ينفذها ولا يمنح تحققًا من سيرفر.</p><a class="text-link" href="index.html#server">فتح My servers</a></section><p>${storageOK?'النتائج تحفظ على هذا المتصفح.':'تعذر الوصول لتخزين المتصفح؛ قد لا تُحفظ النتائج.'} اختبار تدريبي مستقل، وليس اختبار Red Hat الرسمي.</p>`;
document.querySelector('#start-quiz').onclick=()=>start('quiz');document.querySelector('#start-commands').onclick=()=>start('commands');}
function start(type){const items=type==='quiz'?shuffledQuiz():commands;session={type,items,answers:{},submitted:false};root.innerHTML=`<a class="text-link" href="lecture9.html">← صفحة المحاضرة</a><h1>${type==='quiz'?'اختبار الفهم':'اختبار كتابة الأوامر'}</h1><p>${type==='quiz'?'اختر إجابة واحدة لكل سؤال.':'اكتب الصيغة المطلوبة كما في السؤال، بدون علامة prompt. توجد صيغ بديلة مقبولة؛ هذا فحص نصي وليس shell interpreter.'} الحلول تظهر بعد التسليم. لا يوجد مؤقت.</p><div class="exam-bar"><span id="answered" role="status">0 / ${items.length} مجاب</span><span>درجة النجاح 80%</span><button type="submit" form="lecture-form" class="primary">تسليم الاختبار</button></div><form id="lecture-form">${items.map((q,i)=>`<fieldset class="quiz-question"><legend>${i+1}. ${esc(q.question)}</legend>${q.topic?`<p class="topic" dir="ltr">${esc(q.topic)}</p>`:''}${type==='quiz'?q.options.map((o,j)=>`<label><input type="radio" name="answer-${i}" value="${j}"><span>${esc(o)}</span></label>`).join(''):`<label for="command-${i}">الأمر المطلوب</label><input id="command-${i}" name="answer-${i}" type="text" autocomplete="off" spellcheck="false" aria-label="إجابة الأمر ${i+1}">`}</fieldset>`).join('')}<button class="primary" type="submit">تسليم الاختبار</button></form><div id="result" tabindex="-1" aria-live="polite"></div>`;
 const form=document.querySelector('#lecture-form');form.oninput=e=>{if(!e.target.name||session.submitted)return;const i=Number(e.target.name.replace('answer-',''));session.answers[i]=type==='quiz'?Number(e.target.value):e.target.value;document.querySelector('#answered').textContent=Object.values(session.answers).filter(v=>String(v).trim()!=='').length+' / '+items.length+' مجاب'};form.onsubmit=e=>{e.preventDefault();submit()};window.scrollTo(0,0);}
function submit(){if(!session||session.submitted)return;session.submitted=true;const{type,items,answers}=session,r=grade(items,answers,type);saved[type]={best:Math.max(saved[type]?.best??0,r.score),last:r.score,attempts:(saved[type]?.attempts??0)+1};
try{localStorage.setItem(key,JSON.stringify(saved));const p=JSON.parse(localStorage.getItem('rockylab-v1')||'null')||{tasks:{},exams:{},name:'Student'};p.exams??={};p.exams['video9-'+type]={...saved[type],at:new Date().toISOString()};localStorage.setItem('rockylab-v1',JSON.stringify(p))}catch{storageOK=false}
root.querySelectorAll('input,button[type=submit]').forEach(el=>el.disabled=true);const result=document.querySelector('#result');result.innerHTML=`<section class="result"><h2>${r.score}% · ${r.passed?'ناجح':'تحتاج مراجعة'}</h2><p>${r.correct} / ${r.total} صحيحة. الإجابات الفارغة تُحسب خطأ.</p>${!storageOK?'<p>تعذر حفظ النتيجة في المتصفح.</p>':''}<div class="actions"><button id="retry">أعد الاختبار</button><button id="home">العودة للمحاضرة</button></div></section>${items.map((q,i)=>`<article><h2 class="${r.details[i]?'correct':'incorrect'}">${i+1}. ${r.details[i]?'صحيح':'راجع الإجابة'}</h2><p>${esc(q.question)}</p><p class="answer">إجابتك: ${esc(type==='quiz'?(q.options[answers[i]]??'لم تجب'):(answers[i]||'لم تجب'))}</p><p class="answer">الإجابة النموذجية: ${esc(type==='quiz'?q.options[q.answer]:q.accepted[0])}</p><p>${esc(q.explanation)}</p><a class="text-link" target="_blank" rel="noopener" href="${video(q.time)}">راجع المقطع ${stamp(q.time)} ↗</a></article>`).join('')}`;document.querySelector('#retry').onclick=()=>start(type);document.querySelector('#home').onclick=()=>{home();window.scrollTo(0,0)};result.focus();result.scrollIntoView({behavior:'smooth'});}
home();

