// Authored workplace exercises based on the supplied 106-page guide.
// Original PDF and extracted personal examples are deliberately not published.
export const lecturePages={1:'3',2:'4',3:'5–11',4:'12–17',5:'18–21',6:'22–28',7:'29–35',8:'36–40',9:'41–45',10:'46–51',11:'52–57',12:'58–64',13:'65–72',14:'73–82',15:'83–87',16:'88–94',17:'95–99',18:'100–104'};
const pairs=(en,ar)=>({en,ar});
const task=(level,lecture,key,en,ar,den,dar,command,expected,hintEn,hintAr)=>({level,lecture,check:'work-'+key,title:en,titleAR:ar,description:den,descriptionAR:dar,command,expected,hint:hintEn,hintAR:hintAr,simulatorOnly:true});
export const workplaceTasks=[
task(3,3,'handover','Prepare a shift handover','جهّز تقرير تسليم المناوبة','Write the literal text Rocky lab ready to ~/handover.txt, then display it.','اكتب النص Rocky lab ready في ~/handover.txt ثم اعرض الملف.','echo "Rocky lab ready" > ~/handover.txt\ncat ~/handover.txt',{file:'~/handover.txt',text:'Rocky lab ready\n'},'Use > to create the report; cat confirms its contents.','استخدم > لإنشاء التقرير وcat للتحقق من المحتوى.'),
task(3,3,'return-home','Return from an incident investigation','ارجع من فحص العطل','You inspected /var/log. Return to your home and create ~/arrival.txt containing back home.','بعد فحص /var/log ارجع إلى الدليل المنزلي وأنشئ arrival.txt بمحتوى back home.','cd /var/log\ncd ~\necho "back home" > arrival.txt',{file:'~/arrival.txt',text:'back home\n'},'Relative output paths depend on pwd.','مكان الملف النسبي يعتمد على دليل العمل الحالي pwd.'),
task(4,4,'copy-tree','Copy a deployment tree','انسخ شجرة ملفات النشر','Create ~/release/config/app.conf containing port=8080. Copy the entire release directory to ~/release-backup.','أنشئ ~/release/config/app.conf بمحتوى port=8080 وانسخ دليل release كاملاً إلى ~/release-backup.','mkdir -p ~/release/config\necho "port=8080" > ~/release/config/app.conf\ncp -r ~/release ~/release-backup',{file:'~/release-backup/config/app.conf',text:'port=8080\n'},'cp -r copies the directory and its contents.','الخيار -r ينسخ الدليل ومحتوياته بشكل تكراري.'),
task(4,16,'hard-link','Keep data after removing one name','احتفظ بالبيانات بعد حذف أحد الأسماء','Create original.txt with retained data, hard-link it as retained.txt, then remove original.txt.','أنشئ original.txt بمحتوى retained data ثم رابطاً صلباً باسم retained.txt واحذف original.txt.','echo "retained data" > ~/original.txt\nln ~/original.txt ~/retained.txt\nrm ~/original.txt',{file:'~/retained.txt',text:'retained data\n',absent:'~/original.txt'},'A hard link references the same file data. Removing one name does not remove the other.','الرابط الصلب Hard link يشير إلى نفس بيانات الملف؛ حذف اسم لا يحذف الاسم الآخر.'),
task(6,6,'append-log','Maintain an incident timeline','حدّث تسلسل أحداث العطل','Create incident.txt with started, then append resolved on a second line.','أنشئ incident.txt بسطر started وأضف resolved في سطر ثانٍ بدون مسح الأول.','echo started > ~/incident.txt\necho resolved >> ~/incident.txt',{file:'~/incident.txt',text:'started\nresolved\n'},'The second command must preserve the first line.','الأمر الثاني يجب أن يحافظ على السطر الأول.'),
task(6,6,'pipe-report','Save filtered evidence','احفظ أدلة مصفاة','Save only the student account entry from /etc/passwd into ~/student-evidence.txt.','احفظ سطر حساب student فقط من /etc/passwd داخل ~/student-evidence.txt.','grep student /etc/passwd > ~/student-evidence.txt',{file:'~/student-evidence.txt',contains:'student:x:1000:1000:'},'grep selects records; > stores stdout.','grep ينتقي السجلات و > يحفظ الخرج القياسي stdout.'),
task(7,7,'audit-team','Prepare the audit team','جهّز فريق التدقيق','Create the auditors group and the audituser account, then append group membership.','أنشئ مجموعة auditors وحساب audituser ثم أضف عضوية المجموعة بدون استبدال العضويات الأخرى.','sudo groupadd auditors\nsudo useradd -m audituser\nsudo usermod -aG auditors audituser\nid audituser',{group:'auditors',member:'audituser'},'Use -aG, then inspect id audituser.','استخدم -aG وتحقق بواسطة id audituser.'),
task(8,8,'secret','Protect a configuration file','احمِ ملف الإعدادات','Create ~/service.secret and grant only owner read/write permission using symbolic notation.','أنشئ ~/service.secret وامنح المالك فقط صلاحية القراءة والكتابة بالصيغة الرمزية.','touch ~/service.secret\nchmod u=rw,go= ~/service.secret',{file:'~/service.secret',mode:'600'},'u=rw,go= removes permissions from group and others.','u=rw,go= يحدد صلاحيات المالك ويلغي صلاحيات المجموعة والآخرين.'),
task(8,8,'umask','Set defaults for private reports','اضبط الإعداد الافتراضي للتقارير الخاصة','Set umask 077; create ~/private-new.txt and verify that its mode is 600.','اضبط umask على 077 وأنشئ ~/private-new.txt وتحقق أن صلاحياته 600.','umask 077\ntouch ~/private-new.txt\nstat ~/private-new.txt',{file:'~/private-new.txt',mode:'600'},'umask affects new files, not existing ones.','قناع الصلاحيات umask يؤثر على الملفات الجديدة وليس الموجودة سابقاً.'),
task(8,8,'shared-drop','Create a shared drop directory','أنشئ دليل استقبال مشترك','Create ~/drop with mode 1777 so the sticky bit restricts deletion by other users.','أنشئ ~/drop بصلاحيات 1777 لتفعيل Sticky bit وتقييد حذف ملفات الآخرين.','mkdir -p ~/drop\nchmod 1777 ~/drop',{file:'~/drop',mode:'1777',dir:true},'The leading 1 sets the sticky bit.','الرقم 1 في البداية يفعّل Sticky bit.'),
task(10,10,'maintenance','Take a test web service offline','أوقف خدمة الويب التدريبية للصيانة','Install httpd if needed, disable startup, and stop the service. Both states must be off.','ثبّت httpd عند الحاجة ثم عطّل بدءها عند الإقلاع وأوقفها الآن؛ يجب تعطيل الحالتين.','sudo dnf install -y httpd\nsudo systemctl disable --now httpd',{service:'httpd',package:'httpd',active:false,enabled:false},'disabled and inactive are different states. --now handles the current state too.','disabled وinactive حالتان مختلفتان؛ --now يغيّر الحالة الحالية أيضاً.'),
task(12,12,'install-tools','Provision a support utility','ثبّت أداة للدعم الفني','Install the tree package and query the local RPM database.','ثبّت حزمة tree واستعلم عنها من قاعدة RPM المحلية.','sudo dnf install -y tree\nrpm -q tree',{package:'tree'},'DNF installs packages; rpm -q checks installed packages.','DNF يثبت الحزم وrpm -q يستعلم عن الحزم المثبتة.'),
task(14,14,'timezone','Align incident timestamps','وحّد المنطقة الزمنية للسجلات','Set the practice system time zone to Asia/Baghdad.','اضبط المنطقة الزمنية للنظام التدريبي على Asia/Baghdad.','timedatectl list-timezones | grep Baghdad\nsudo timedatectl set-timezone Asia/Baghdad\ntimedatectl',{timezone:'Asia/Baghdad'},'The time zone changes local display, not the underlying UTC instant.','المنطقة الزمنية تغيّر عرض الوقت المحلي ولا تغيّر اللحظة الأساسية بتوقيت UTC.'),
task(14,14,'ntp','Enable time synchronization','فعّل مزامنة الوقت','Enable NTP in the practice clock state and inspect the result.','فعّل NTP في حالة الساعة التدريبية وافحص النتيجة.','sudo timedatectl set-ntp true\ntimedatectl',{ntp:true},'A real host also needs a working time service and reachable sources.','الجهاز الحقيقي يحتاج خدمة وقت عاملة ومصادر مزامنة يمكن الوصول إليها.'),
task(14,14,'incident-log','Record a recovery event','سجّل حدث استعادة الخدمة','Send recovered web service to the journal with logger.','أرسل الرسالة recovered web service إلى Journal بواسطة logger.','logger -p user.notice "recovered web service"\njournalctl -n 20',{log:'recovered web service'},'Read the message back to connect the action with evidence.','راجع الرسالة بعد كتابتها لربط الإجراء بالدليل.'),
task(16,15,'backup-release','Back up a release before a change','انسخ الإصدار احتياطياً قبل التغيير','Create ~/deploy/app.conf containing version=1 and archive deploy into ~/deploy.tar.gz.','أنشئ ~/deploy/app.conf بمحتوى version=1 وأرشف deploy داخل ~/deploy.tar.gz.','mkdir -p ~/deploy\necho "version=1" > ~/deploy/app.conf\ntar -czf ~/deploy.tar.gz -C ~ deploy',{archive:'~/deploy.tar.gz',member:'deploy/app.conf',text:'version=1\n'},'List the archive before restoring it.','اعرض فهرس الأرشيف قبل الاستعادة.'),
task(16,15,'restore-release','Recover the original configuration','استعد الإعدادات الأصلية','Restore deploy.tar.gz into ~/recovery and confirm app.conf still contains version=1.','استخرج deploy.tar.gz داخل ~/recovery وتحقق أن app.conf يحتوي version=1.','mkdir -p ~/recovery\ntar -xzf ~/deploy.tar.gz -C ~/recovery\ncat ~/recovery/deploy/app.conf',{file:'~/recovery/deploy/app.conf',text:'version=1\n'},'An archive is not a verified backup until its data can be restored.','لا يُعد النسخ الاحتياطي موثوقاً حتى تُختبر استعادة بياناته.'),
];
export function passesWorkplace(shell,key){const e=workplaceTasks.find(t=>t.check===key)?.expected;if(!e)return false;const n=e.file?shell.node(e.file):null;if(e.file&&!n)return false;if(e.text!==undefined&&e.file&&n.text!==e.text)return false;if(e.contains&&!n.text?.includes(e.contains))return false;if(e.mode&&n.mode!==e.mode)return false;if(e.dir&&!n.dir)return false;if(e.absent&&shell.node(e.absent))return false;if(e.group&&!shell.groups[e.group]?.includes(e.member))return false;if(e.service&&(!shell.services[e.service]||shell.services[e.service].active!==e.active||shell.services[e.service].enabled!==e.enabled))return false;if(e.package&&!shell.packages.has(e.package))return false;if(e.timezone&&shell.timezone!==e.timezone)return false;if(e.ntp!==undefined&&shell.ntp!==e.ntp)return false;if(e.log&&!shell.logs.some(x=>x.includes(e.log)))return false;if(e.archive&&shell.archives[shell.path(e.archive)]?.[e.member]?.text!==e.text)return false;return true;}
export function extendCurriculum(levels){
 if(levels.some(l=>l.id===26))return;
 const realTask=(lecture,title,description,command,check,hint)=>({lecture,title,description,command,check,hint,real:true});
 const q=(lecture,question,options,answer,explanation)=>({lecture,question,options,answer,explanation});
 levels.push({id:25,lecture:17,title:'Virtual machines: inspect and recover',category:'Virtualization',source:'RH124',difficulty:'Intermediate',pages:lecturePages[17],description:'Inspect a real KVM host, inventory guests, and diagnose the virtualization service.',concept:'KVM يشغّل الآلات الافتراضية، وlibvirt يديرها، وvirsh واجهة أوامر. المحاضرة تستخدم RHEL 7؛ في Rocky الحديث قد تعمل خدمات libvirt المعيارية مثل virtqemud. افحص النسخة والخدمات المتاحة قبل تطبيق الأوامر. استخدم virsh shutdown للإيقاف الطبيعي؛ destroy قطع فوري للطاقة الافتراضية.',tasks:[
 realTask(17,'Inspect KVM support','On a prepared Rocky virtualization host, inspect architecture and loaded KVM modules.','arch\nlsmod | grep kvm','kvm-inspect','If nested virtualization is unavailable, enable it in the outer hypervisor or use a capable host.'),
 realTask(17,'Inventory every guest','Connect to the system libvirt instance and list running and stopped guests.','virsh -c qemu:///system list --all','vm-inventory','An empty list is a valid inventory. Permission denied is not success.'),
 realTask(17,'Inspect the management socket','Inspect the modular QEMU socket used by modern libvirt. On older installations inspect libvirtd instead.','systemctl status virtqemud.socket','vm-daemon','Use systemctl status libvirtd if the host uses the monolithic daemon.')],quiz:[
 q(17,'Which inventory includes stopped VMs?',['virsh list --all','virsh list','ip route'],0,'--all includes guests that are shut off.'),q(17,'What does virsh destroy do?',['Immediately stops the VM','Deletes its disk image','Gracefully shuts down the guest'],0,'It is equivalent to cutting power; prefer shutdown when possible.'),q(17,'A guest cannot open its disk. Inspect…',['Image path, ownership, permissions and SELinux labels','Only the DNS server','The terminal font'],0,'Use service logs and verify the disk access path before retrying.')]});
 levels.push({id:26,lecture:18,title:'VNC over an SSH tunnel',category:'Remote access',source:'RH124',difficulty:'Advanced',pages:lecturePages[18],description:'Inspect a prepared TigerVNC host and access its desktop through SSH.',concept:'VNC يوفر جلسة سطح مكتب رسومية. العرض :1 يرتبط عادةً بمنفذ 5901. في TigerVNC الحديث عيّن المستخدم في /etc/tigervnc/vncserver.users واضبط جلسة سطح المكتب المدعومة حسب وثائق النسخة. لا تنسخ تعديل unit القديم من RHEL 7 إلى Rocky دون مراجعته. أنشئ كلمة VNC بنفسك عبر vncpasswd، واحتفظ بـ SELinux والجدار الناري مفعّلين.',tasks:[
 realTask(18,'Verify server installation','On the VNC server, query the installed TigerVNC server package.','rpm -q tigervnc-server','vnc-package','Install with sudo dnf install tigervnc-server if missing. A desktop session is also required.'),
 realTask(18,'Verify the configured display','After assigning a non-root user to display :1 and setting its VNC password interactively, check the service.','systemctl status vncserver@:1.service','vnc-service','Modern configuration uses /etc/tigervnc/vncserver.users, for example :1=vncuser. Consult the packaged HOWTO for your version.'),
 realTask(18,'Inspect the display listener','Confirm a listener on TCP 5901. From your own desktop use vncviewer -via vncuser@SERVER_IP localhost:1 to view it.','ss -tlnp | grep 5901','vnc-listener','A listening socket verifies the listener, not the graphical desktop. Final desktop verification happens in your VNC viewer.')],quiz:[
 q(18,'Display :1 normally uses which TCP port?',['5901','5900','22'],0,'The usual mapping is 5900 plus the display number.'),q(18,'What should remain enabled while diagnosing VNC?',['SELinux and the firewall','Only the browser','No security services'],0,'Diagnose policy and service configuration instead of disabling protections.'),q(18,'vncviewer -via establishes…',['An SSH tunnel for VNC','A new Linux user','A disk backup'],0,'The viewer connects to the remote display through SSH.')]});
 const map={15:16,16:15,20:16};
 for(const l of levels){l.lecture=l.lecture||(l.id<=14?l.id:map[l.id]||null);l.pages=l.lecture?lecturePages[l.lecture]:'—';for(const t of l.tasks)t.lecture=l.lecture;for(const q of l.quiz)q.lecture=l.lecture;}
 for(const task of workplaceTasks)levels.find(l=>l.id===task.level).tasks.push(task);
 levels.find(l=>l.id===16).tasks[0].command='mkdir -p ~/project/docs\necho "Rocky Linux" > ~/project/docs/notes.txt\ntar -czf ~/project.tar.gz -C ~ project';
 const supported=['disks','rootmount','cut-users','unique-users','archive','archive-list','restore','disk-types','capacity','inodes'];
 for(const l of levels)for(const t of l.tasks)if(supported.includes(t.check))t.real=false;
}

